export {default as AuthRouter} from './auth.route'
export {default as BadgeRouter} from './badge.route'
export {default as CategoriesRouter} from './category.route'
export {default as HomeSliderRouter} from './homeSlider.route'
export {default as SupplierRouter} from './supplier.route'
export {default as ProductRouter} from './product.route'
export {default as TopCategoryRouter} from './topCategory.route'
export {default as ServiceRouter} from './service.route'