"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PlanRouter = exports.HomePageRouter = exports.ServiceRouter = exports.TopCategoryRouter = exports.ProductRouter = exports.SupplierRouter = exports.HomeSliderRouter = exports.CategoriesRouter = exports.BadgeRouter = exports.AuthRouter = void 0;
var auth_route_1 = require("./auth.route");
Object.defineProperty(exports, "AuthRouter", { enumerable: true, get: function () { return auth_route_1.default; } });
var badge_route_1 = require("./badge.route");
Object.defineProperty(exports, "BadgeRouter", { enumerable: true, get: function () { return badge_route_1.default; } });
var category_route_1 = require("./category.route");
Object.defineProperty(exports, "CategoriesRouter", { enumerable: true, get: function () { return category_route_1.default; } });
var homeSlider_route_1 = require("./homeSlider.route");
Object.defineProperty(exports, "HomeSliderRouter", { enumerable: true, get: function () { return homeSlider_route_1.default; } });
var supplier_route_1 = require("./supplier.route");
Object.defineProperty(exports, "SupplierRouter", { enumerable: true, get: function () { return supplier_route_1.default; } });
var product_route_1 = require("./product.route");
Object.defineProperty(exports, "ProductRouter", { enumerable: true, get: function () { return product_route_1.default; } });
var topCategory_route_1 = require("./topCategory.route");
Object.defineProperty(exports, "TopCategoryRouter", { enumerable: true, get: function () { return topCategory_route_1.default; } });
var service_route_1 = require("./service.route");
Object.defineProperty(exports, "ServiceRouter", { enumerable: true, get: function () { return service_route_1.default; } });
var homePage_route_1 = require("./homePage.route");
Object.defineProperty(exports, "HomePageRouter", { enumerable: true, get: function () { return homePage_route_1.default; } });
var plan_route_1 = require("./plan.route");
Object.defineProperty(exports, "PlanRouter", { enumerable: true, get: function () { return plan_route_1.default; } });
//# sourceMappingURL=index.js.map